### ISSUE TITLE
Квадратное уравнение

### ISSUE THREAD

**Issue by ankutalev** [denisenes/19214_denisenes#1]
1) Дискриминант считается два раза - домашка считать квадратные уравнения идет не просто так после вложенных функций
2) Ужас с гвардсами на граничные условия можно переписать паттерн матчингом - выйдет гораздо красивей и писать меньше

**Comment by denisenes** [comment]
Здравствуйте, сделал необходимые исправления

**Comment by ankutalev** [comment]
Отрицательный дискриминант потерял

**Comment by denisenes** [comment]
Поправил, проверьте

**Comment by ankutalev** [comment]
принято
